import type { Lawyer, Profile, Review, Case, CaseLawyerRecommendation } from '../types';

// Dummy profiles
export const dummyProfiles: Profile[] = [
  {
    id: '1',
    full_name: 'Adv. Rajesh Kumar',
    phone: '+91 98765 43210',
    city: 'Delhi',
    state: 'Delhi',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    full_name: 'Adv. Priya Sharma',
    phone: '+91 98123 45678',
    city: 'Mumbai',
    state: 'Maharashtra',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    full_name: 'Adv. Amit Verma',
    phone: '+91 99887 76543',
    city: 'Delhi',
    state: 'Delhi',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    full_name: 'Adv. Meena Krishnan',
    phone: '+91 88765 43210',
    city: 'Chennai',
    state: 'Tamil Nadu',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    full_name: 'Adv. Vikram Singh',
    phone: '+91 77654 32109',
    city: 'Jaipur',
    state: 'Rajasthan',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    full_name: 'Adv. Sunita Patel',
    phone: '+91 66543 21098',
    city: 'Ahmedabad',
    state: 'Gujarat',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    full_name: 'Adv. Arjun Reddy',
    phone: '+91 55432 10987',
    city: 'Hyderabad',
    state: 'Telangana',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    full_name: 'Adv. Kavita Nair',
    phone: '+91 44321 09876',
    city: 'Bangalore',
    state: 'Karnataka',
    avatar_url: null,
    role: 'lawyer',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Dummy lawyers
export const dummyLawyers: (Lawyer & { profiles: Profile; reviews: Review[] })[] = [
  {
    id: '1',
    profile_id: '1',
    bar_registration_number: 'BAR/2010/12345',
    specialization: ['Property', 'Civil', 'Real Estate'],
    years_experience: 15,
    courts_served: ['District Court', 'High Court'],
    languages_spoken: ['English', 'Hindi'],
    biography: 'Experienced property lawyer specializing in land disputes, boundary conflicts, and real estate matters. Successfully resolved over 200 property disputes with a focus on fast-track resolution through mediation.',
    education: ['LLB, Delhi University (2010)', 'LLM in Property Law, NLSIU Bangalore (2013)'],
    certification_urls: [],
    office_address: 'Chamber 45, District Court Complex, Tis Hazari, Delhi',
    consultation_fee: 2000,
    average_case_fee_min: 50000,
    average_case_fee_max: 200000,
    success_rate: 92,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '10:00', end: '17:00', available: true },
      tuesday: { start: '10:00', end: '17:00', available: true },
      wednesday: { start: '10:00', end: '17:00', available: true },
      thursday: { start: '10:00', end: '17:00', available: true },
      friday: { start: '10:00', end: '17:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[0],
    reviews: [
      { id: 'r1', lawyer_id: '1', user_id: 'u1', consultation_id: 'c1', rating: 5, review_text: 'Excellent lawyer! Solved my property dispute within 3 months. Very professional and responsive.', created_at: new Date().toISOString() },
      { id: 'r2', lawyer_id: '1', user_id: 'u2', consultation_id: 'c2', rating: 5, review_text: 'Highly recommended for property cases. Clear communication and reasonable fees.', created_at: new Date().toISOString() },
      { id: 'r3', lawyer_id: '1', user_id: 'u3', consultation_id: 'c3', rating: 4, review_text: 'Good experience overall. Case was resolved successfully.', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '2',
    profile_id: '2',
    bar_registration_number: 'BAR/2012/54321',
    specialization: ['Family', 'Divorce', 'Civil'],
    years_experience: 12,
    courts_served: ['Family Court', 'District Court', 'High Court'],
    languages_spoken: ['English', 'Hindi', 'Marathi'],
    biography: 'Compassionate family lawyer with expertise in divorce proceedings, child custody, and alimony cases. Committed to achieving amicable settlements while protecting client interests.',
    education: ['LLB, Mumbai University (2012)', 'Diploma in Family Law (2014)'],
    certification_urls: [],
    office_address: 'Suite 12, Family Court Building, Bandra, Mumbai',
    consultation_fee: 1500,
    average_case_fee_min: 40000,
    average_case_fee_max: 150000,
    success_rate: 89,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '09:00', end: '18:00', available: true },
      tuesday: { start: '09:00', end: '18:00', available: true },
      wednesday: { start: '09:00', end: '18:00', available: true },
      thursday: { start: '09:00', end: '14:00', available: true },
      friday: { start: '09:00', end: '18:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[1],
    reviews: [
      { id: 'r4', lawyer_id: '2', user_id: 'u4', consultation_id: 'c4', rating: 5, review_text: 'Priya helped me through a difficult divorce. She was understanding and fought for my rights.', created_at: new Date().toISOString() },
      { id: 'r5', lawyer_id: '2', user_id: 'u5', consultation_id: 'c5', rating: 4, review_text: 'Professional and empathetic. Got me a fair settlement.', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '3',
    profile_id: '3',
    bar_registration_number: 'BAR/2018/98765',
    specialization: ['Criminal', 'Civil'],
    years_experience: 8,
    courts_served: ['District Court', 'Sessions Court'],
    languages_spoken: ['English', 'Hindi'],
    biography: 'Dedicated criminal defense attorney with experience in bail applications, trial defense, and appeals. Known for thorough case preparation and strong courtroom presence.',
    education: ['LLB, Delhi University (2018)'],
    certification_urls: [],
    office_address: 'Chamber 78, Tis Hazari Courts, Delhi',
    consultation_fee: 1000,
    average_case_fee_min: 30000,
    average_case_fee_max: 100000,
    success_rate: 85,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '10:00', end: '17:00', available: true },
      tuesday: { start: '10:00', end: '17:00', available: true },
      wednesday: { start: '10:00', end: '17:00', available: true },
      friday: { start: '10:00', end: '15:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[2],
    reviews: [
      { id: 'r6', lawyer_id: '3', user_id: 'u6', consultation_id: 'c6', rating: 5, review_text: 'Got my bail approved in just 2 days. Excellent knowledge of criminal law.', created_at: new Date().toISOString() },
      { id: 'r7', lawyer_id: '3', user_id: 'u7', consultation_id: 'c7', rating: 4, review_text: 'Professional service at affordable rates.', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '4',
    profile_id: '4',
    bar_registration_number: 'BAR/2011/11111',
    specialization: ['Corporate', 'Tax', 'Intellectual Property'],
    years_experience: 14,
    courts_served: ['High Court', 'Supreme Court'],
    languages_spoken: ['English', 'Hindi', 'Tamil'],
    biography: 'Corporate law specialist with extensive experience in M&A, contract drafting, and tax planning. Advised numerous startups and Fortune 500 companies on legal compliance.',
    education: ['LLB, NLSIU Bangalore (2011)', 'Company Secretary (2012)'],
    certification_urls: [],
    office_address: 'Tower A, IT Park, OMR Road, Chennai',
    consultation_fee: 5000,
    average_case_fee_min: 100000,
    average_case_fee_max: 500000,
    success_rate: 95,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '09:00', end: '18:00', available: true },
      tuesday: { start: '09:00', end: '18:00', available: true },
      wednesday: { start: '09:00', end: '18:00', available: true },
      thursday: { start: '09:00', end: '18:00', available: true },
      friday: { start: '09:00', end: '16:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[3],
    reviews: [
      { id: 'r8', lawyer_id: '4', user_id: 'u8', consultation_id: 'c8', rating: 5, review_text: 'Helped structure our startup perfectly. Invaluable advice on IP protection.', created_at: new Date().toISOString() },
      { id: 'r9', lawyer_id: '4', user_id: 'u9', consultation_id: 'c9', rating: 5, review_text: 'Exceptional knowledge of corporate taxation. Saved us lakhs.', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '5',
    profile_id: '5',
    bar_registration_number: 'BAR/2015/22222',
    specialization: ['Property', 'Civil', 'Consumer'],
    years_experience: 10,
    courts_served: ['District Court', 'Consumer Court'],
    languages_spoken: ['English', 'Hindi', 'Rajasthani'],
    biography: 'Experienced in property documentation, consumer complaints, and civil disputes. Known for achieving favorable settlements without prolonged litigation.',
    education: ['LLB, Rajasthan University (2015)', 'Diploma in Consumer Law (2016)'],
    certification_urls: [],
    office_address: 'Law Chambers, M.I. Road, Jaipur',
    consultation_fee: 1200,
    average_case_fee_min: 35000,
    average_case_fee_max: 120000,
    success_rate: 88,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '10:00', end: '17:00', available: true },
      tuesday: { start: '10:00', end: '17:00', available: true },
      wednesday: { start: '10:00', end: '17:00', available: true },
      thursday: { start: '10:00', end: '17:00', available: true },
      friday: { start: '10:00', end: '17:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[4],
    reviews: [
      { id: 'r10', lawyer_id: '5', user_id: 'u10', consultation_id: 'c10', rating: 4, review_text: 'Won my consumer case against a builder. Very helpful!', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '6',
    profile_id: '6',
    bar_registration_number: 'BAR/2016/33333',
    specialization: ['Employment', 'Corporate', 'Labour Law'],
    years_experience: 9,
    courts_served: ['District Court', 'Labour Court', 'High Court'],
    languages_spoken: ['English', 'Hindi', 'Gujarati'],
    biography: 'Employment law expert helping employees and employers navigate workplace disputes, wrongful termination, and labor compliance matters.',
    education: ['LLB, Gujarat National Law University (2016)'],
    certification_urls: [],
    office_address: 'Corporate Law House, CG Road, Ahmedabad',
    consultation_fee: 1800,
    average_case_fee_min: 45000,
    average_case_fee_max: 180000,
    success_rate: 87,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '09:00', end: '17:00', available: true },
      tuesday: { start: '09:00', end: '17:00', available: true },
      wednesday: { start: '09:00', end: '17:00', available: true },
      thursday: { start: '09:00', end: '17:00', available: true },
      friday: { start: '09:00', end: '17:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[5],
    reviews: [
      { id: 'r11', lawyer_id: '6', user_id: 'u11', consultation_id: 'c11', rating: 5, review_text: 'Got me my full severance pay after wrongful termination. Highly competent!', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '7',
    profile_id: '7',
    bar_registration_number: 'BAR/2019/44444',
    specialization: ['Cyber Crime', 'Intellectual Property', 'Corporate'],
    years_experience: 6,
    courts_served: ['District Court', 'Cyber Appellate Tribunal'],
    languages_spoken: ['English', 'Hindi', 'Telugu'],
    biography: 'Specializes in cybercrime defense, data privacy compliance, and IP protection in the digital age. Worked with major tech companies on data breach responses.',
    education: ['LLB, NALSAR Hyderabad (2019)', 'Certification in Cyber Law (2020)'],
    certification_urls: [],
    office_address: 'Tech Park, HITEC City, Hyderabad',
    consultation_fee: 2500,
    average_case_fee_min: 60000,
    average_case_fee_max: 250000,
    success_rate: 90,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '10:00', end: '18:00', available: true },
      tuesday: { start: '10:00', end: '18:00', available: true },
      wednesday: { start: '10:00', end: '18:00', available: true },
      thursday: { start: '10:00', end: '18:00', available: true },
      friday: { start: '10:00', end: '15:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[6],
    reviews: [
      { id: 'r12', lawyer_id: '7', user_id: 'u12', consultation_id: 'c12', rating: 5, review_text: 'Helped us recover from a major cyber attack and navigate legal requirements.', created_at: new Date().toISOString() },
    ],
  },
  {
    id: '8',
    profile_id: '8',
    bar_registration_number: 'BAR/2017/55555',
    specialization: ['Immigration', 'Corporate', 'Civil'],
    years_experience: 7,
    courts_served: ['High Court', 'District Court'],
    languages_spoken: ['English', 'Hindi', 'Kannada', 'Tamil'],
    biography: 'Immigration law specialist handling visa applications, citizenship matters, and deportation defense. Successfully processed 500+ visa applications.',
    education: ['LLB, National Law School of India University (2017)'],
    certification_urls: [],
    office_address: 'Immigration House, MG Road, Bangalore',
    consultation_fee: 3000,
    average_case_fee_min: 50000,
    average_case_fee_max: 200000,
    success_rate: 93,
    is_verified: true,
    verification_status: 'verified',
    availability: {
      monday: { start: '09:00', end: '17:00', available: true },
      tuesday: { start: '09:00', end: '17:00', available: true },
      wednesday: { start: '09:00', end: '17:00', available: true },
      thursday: { start: '09:00', end: '17:00', available: true },
      friday: { start: '09:00', end: '17:00', available: true },
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: dummyProfiles[7],
    reviews: [
      { id: 'r13', lawyer_id: '8', user_id: 'u13', consultation_id: 'c13', rating: 5, review_text: 'Got my H1B approved on first attempt. Expert immigration lawyer!', created_at: new Date().toISOString() },
      { id: 'r14', lawyer_id: '8', user_id: 'u14', consultation_id: 'c14', rating: 4, review_text: 'Professional service, clear guidance throughout the process.', created_at: new Date().toISOString() },
    ],
  },
];

// Dummy cases
export const dummyCases: Case[] = [
  {
    id: 'case-1',
    user_id: 'user-1',
    title: 'Property Boundary Dispute with Neighbor',
    description: 'My neighbor has constructed a wall that encroaches on my property by approximately 2 feet. We have a registered survey map from 2015 that clearly shows the boundary lines. The neighbor refuses to remove the wall despite multiple requests.',
    case_type: 'Property',
    court_type: 'District Court',
    state: 'Delhi',
    city: 'Delhi',
    hearing_location: 'Tis Hazari Courts',
    budget_min: 50000,
    budget_max: 150000,
    budget_type: 'negotiable',
    preferences: {
      local_lawyer: true,
      virtual_consultation: true,
      language_preference: 'English',
    },
    document_urls: [],
    ai_analysis: {
      summary: 'This is a clear property encroachment case with documented evidence through survey maps.',
      category: 'Property Dispute',
      complexity: 'medium',
      suggested_strategy: '1. Gather all property documents and survey reports\n2. Send legal notice\n3. File civil suit if no resolution',
      estimated_timeline: '6-18 months',
      estimated_cost_min: 50000,
      estimated_cost_max: 150000,
      confidence_score: 92,
    },
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Dummy recommendations
export const getRecommendationsForCase = (caseType: string) => {
  const recommendedLawyers = dummyLawyers
    .filter(lawyer => lawyer.specialization.some(s => s.toLowerCase().includes(caseType.toLowerCase())))
    .slice(0, 5);

  return recommendedLawyers.map((lawyer, index) => ({
    id: `rec-${index}`,
    case_id: 'case-1',
    lawyer_id: lawyer.id,
    recommendation_score: Math.max(70, 95 - index * 5),
    recommendation_reason: `${lawyer.years_experience}+ years in ${lawyer.specialization[0]}, ${(lawyer.reviews || []).length} client reviews, located in ${lawyer.profiles.city}.`,
    estimated_fee: lawyer.average_case_fee_min + Math.floor((lawyer.average_case_fee_max - lawyer.average_case_fee_min) / 2),
    created_at: new Date().toISOString(),
    lawyer,
  }));
};
